# Generated by Django 4.2.16 on 2025-01-24 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.IntegerField(max_length=2, primary_key=True, serialize=False)),
                ('brand', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=50)),
                ('hp', models.IntegerField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('untill', models.DateField()),
                ('car', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='carrent.car')),
            ],
        ),
    ]
