# Generated by Django 4.2.16 on 2025-01-24 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrent', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='hp',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='car',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
