# Generated by Django 4.2.16 on 2025-01-31 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carrent', '0002_alter_car_hp_alter_car_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('drivinglicense', models.DateField()),
                ('age', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cleanIn', models.BooleanField(default=True)),
                ('cleanOut', models.BooleanField(default=True)),
                ('tires', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='car',
            name='condition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='carrent.condition'),
        ),
        migrations.AddField(
            model_name='rental',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='carrent.client'),
        ),
    ]
