# Generated by Django 4.2.16 on 2025-01-31 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrent', '0003_client_condition_car_condition_rental_client'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'ordering': ['id', 'brand']},
        ),
        migrations.RenameField(
            model_name='client',
            old_name='drivinglicense',
            new_name='drivingLicenseUntill',
        ),
        migrations.AddField(
            model_name='car',
            name='drive',
            field=models.CharField(default='4x4', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='drivingLicense',
            field=models.BooleanField(default=True),
        ),
    ]
