# Generated by Django 4.2.16 on 2025-01-31 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carrent', '0004_alter_car_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['firstname', 'lastname']},
        ),
    ]
